package main

import (
	"time"

	"github.com/google/uuid"
	"github.com/jessie-sr/rss-aggregator/internal/db"
)

// Custom model.go as an abstraction layer between the application and the db schema generated by sqlc
type User struct {
	ID        uuid.UUID `json:"id"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
	Name      string    `json:"name"`
	ApiKey    string    `json:"api_key"`
}

type Feed struct {
	ID        uuid.UUID `json:"id"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
	Name      string    `json:"name"`
	Url       string    `json:"url"`
	UserID    uuid.UUID `json:"user_id"`
}

type FeedSaved struct {
	ID        uuid.UUID `json:"id"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
	UserID    uuid.UUID `json:"user_id"`
	FeedID    uuid.UUID `json:"feed_id"`
}

func dbUserToUser(dbUser db.User) User {
	return User{
		ID:        dbUser.ID,
		CreatedAt: dbUser.CreatedAt,
		UpdatedAt: dbUser.UpdatedAt,
		Name:      dbUser.Name,
		ApiKey:    dbUser.ApiKey,
	}
}

func dbFeedToFeed(dbFeed db.Feed) Feed {
	return Feed{
		ID:        dbFeed.ID,
		CreatedAt: dbFeed.CreatedAt,
		UpdatedAt: dbFeed.UpdatedAt,
		Name:      dbFeed.Name,
		Url:       dbFeed.Url,
		UserID:    dbFeed.UserID,
	}
}

func dbFeedsToFeeds(dbFeeds []db.Feed) []Feed {
	feeds := []Feed{}
	for _, dbFeed := range dbFeeds {
		feeds = append(feeds, dbFeedToFeed(dbFeed))
	}
	return feeds
}

func dbFeedSavedToFeedSaved(dbFeedSaved db.FeedSaved) FeedSaved {
	return FeedSaved{
		ID:        dbFeedSaved.ID,
		CreatedAt: dbFeedSaved.CreatedAt,
		UpdatedAt: dbFeedSaved.UpdatedAt,
		UserID:    dbFeedSaved.UserID,
		FeedID:    dbFeedSaved.FeedID,
	}
}

func dbSavedFeedsToSavedFeeds(dbSavedFeeds []db.FeedSaved) []FeedSaved {
	saved_feeds := []FeedSaved{}
	for _, dbFeedSaved := range dbSavedFeeds {
		saved_feeds = append(saved_feeds, dbFeedSavedToFeedSaved(dbFeedSaved))
	}
	return saved_feeds
}
