// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: feed_saved.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createFeedSaved = `-- name: CreateFeedSaved :one
INSERT INTO feed_saved (id, created_at, updated_at, user_id, feed_id)
VALUES ($1, $2, $3, $4, $5
)
RETURNING id, created_at, updated_at, user_id, feed_id
`

type CreateFeedSavedParams struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	UserID    uuid.UUID
	FeedID    uuid.UUID
}

func (q *Queries) CreateFeedSaved(ctx context.Context, arg CreateFeedSavedParams) (FeedSaved, error) {
	row := q.db.QueryRowContext(ctx, createFeedSaved,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.UserID,
		arg.FeedID,
	)
	var i FeedSaved
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.FeedID,
	)
	return i, err
}
